# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0005_auto_20160609_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 34, 4, 940244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 34, 4, 940275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 34, 4, 939190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 34, 4, 939488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
