# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0006_auto_20160609_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 57, 23, 629529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 57, 23, 629562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('drafting', 'Drafting'), ('finished', 'Finished'), ('discarded', 'Discarded')], default='drafting', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 57, 23, 628450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 18, 57, 23, 628812, tzinfo=utc)),
        ),
    ]
