# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0007_auto_20160609_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 504352, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 504816, tzinfo=utc))),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='historyentry',
            name='story',
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['order'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 503052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 503079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 502091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 7, 26, 502331, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='HistoryEntry',
        ),
        migrations.AddField(
            model_name='fragment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='storybook.Story'),
        ),
        migrations.AddField(
            model_name='draft',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='storybook.Story'),
        ),
        migrations.AddField(
            model_name='character',
            name='scenes',
            field=models.ManyToManyField(related_name='characters', to='storybook.Scene'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='storybook.Story'),
        ),
    ]
