# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0008_auto_20160610_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default='#000', max_length=50),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 296315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 297038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 294197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 294231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 293143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 10, 21, 21, 10, 293407, tzinfo=utc)),
        ),
    ]
