# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0009_auto_20160610_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, default='#000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 95265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 95739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 93854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scene',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 93886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 92860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 17, 59, 54, 93106, tzinfo=utc)),
        ),
    ]
