# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0013_auto_20170317_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='scene_text',
            new_name='text',
        ),
    ]
