# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0014_auto_20170317_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['created']},
        ),
    ]
