# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0016_scene_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
