# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0018_auto_20170616_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InboxEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='storybook.Inbox')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
