# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0020_auto_20170713_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
